#: Kept equal to ``[project] version`` in pyproject.toml by
#: ``test_release_readiness.test_package_version_matches_project_metadata``.
#: Deliberately absent from ``__all__``: dunders are not part of the exported
#: name surface, and ``from ... import *`` must not shadow a caller's own.
__version__ = "1.0.0"

from .client import SrtClient
from .config import SrtConfig
from .consent import (
    MutationConsent,
    MutationPreview,
    require_card_kind_claim,
    require_mutation_consent,
)
from .errors import (
    SrtApiError,
    SrtAppError,
    SrtAuthError,
    SrtInvalidRequestError,
    SrtIpBlockedError,
    SrtMutationNotAllowedError,
    SrtNetFunnelError,
    SrtNetFunnelKeyError,
    SrtNoDirectTrainError,
    SrtNoResultsError,
    SrtProtocolError,
    SrtQueueRejectedError,
    SrtSeatUnavailableError,
    SrtSessionExpiredError,
    SrtTransportError,
    classify_app_error,
)
from .models import (
    DiscountCoupon,
    DiscountCouponList,
    FareItem,
    FarePage,
    HtmlPage,
    MutualVerificationResult,
    Notice,
    NoticeListResult,
    PassengerCounts,
    PublicDiscountEntitlement,
    PublicDiscountPage,
    PublicDiscountSelection,
    SeatCarOption,
    SeatDesignation,
    SeatGrid,
    SeatGridSeat,
    SeatSelectionPage,
    SeatType,
    SrtCancelResult,
    SrtCouponRegistrationResult,
    SrtPaymentCard,
    SrtPaymentResult,
    SrtRefundResult,
    SrtRefundTicketInfo,
    SrtReservationHold,
    SrtReservationListResult,
    SrtReservationSummary,
    SrtSession,
    TimetablePage,
    TimetableRow,
    TrainSearchQuery,
    TrainSearchMetadata,
    TrainSearchResult,
    TrainSummary,
    TransferItinerary,
    TransferSearchResult,
    UnpairedTransferGroup,
)

#: Deliberately NOT re-exported here: ``parsers`` and the request/attempt models
#: that only its functions produce. ``SrtClient`` already calls every one of
#: those parsers on the caller's behalf, so a caller who imports one is reaching
#: past the client into the wire layer. They remain importable at their defining
#: path -- ``from srt_mobile_api.parsers import ...``,
#: ``from srt_mobile_api.models import ...`` -- because this is a move, not a
#: deletion. ``tests/test_public_surface_rule.py`` is what keeps them down.

__all__ = [
    "SrtClient",
    "SrtConfig",
    "MutationConsent",
    "MutationPreview",
    "require_card_kind_claim",
    "require_mutation_consent",
    "SrtApiError",
    "SrtAppError",
    "SrtAuthError",
    "SrtInvalidRequestError",
    "SrtIpBlockedError",
    "SrtMutationNotAllowedError",
    "SrtNetFunnelError",
    "SrtNetFunnelKeyError",
    "SrtNoDirectTrainError",
    "SrtNoResultsError",
    "SrtProtocolError",
    "SrtQueueRejectedError",
    "SrtSeatUnavailableError",
    "SrtSessionExpiredError",
    "SrtTransportError",
    "classify_app_error",
    "DiscountCoupon",
    "DiscountCouponList",
    "FareItem",
    "FarePage",
    "HtmlPage",
    "MutualVerificationResult",
    "Notice",
    "NoticeListResult",
    "PassengerCounts",
    "PublicDiscountEntitlement",
    "PublicDiscountPage",
    "PublicDiscountSelection",
    "SeatCarOption",
    "SeatDesignation",
    "SeatGrid",
    "SeatGridSeat",
    "SeatSelectionPage",
    "SeatType",
    "SrtCancelResult",
    "SrtCouponRegistrationResult",
    "SrtPaymentCard",
    "SrtPaymentResult",
    "SrtRefundResult",
    "SrtRefundTicketInfo",
    "SrtReservationHold",
    "SrtReservationListResult",
    "SrtReservationSummary",
    "SrtSession",
    "TimetablePage",
    "TimetableRow",
    "TrainSearchQuery",
    "TrainSearchMetadata",
    "TrainSearchResult",
    "TrainSummary",
    "TransferItinerary",
    "TransferSearchResult",
    "UnpairedTransferGroup",
]
